theme: jekyll-theme-slate
author: Vaibhav Mathur
email: vaibhavmathur117@gmail.com
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'

contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'

  # Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]